version: '2'

services:
    django:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
    redis:
        restart: always
        image: redis:3.2.5-alpine
        expose:
          - 6379
        volumes:
          - ./docker/redis/data:/data
