version: '2'

services:
    backend:
        extends:
            file: docker-common.yml
            service: django
        entrypoint:
            - /django-entrypoint.sh
        links:
            - redis
        ports:
            - "12000:12000"
        expose:
            - 12000
    worker:
        extends:
            file: docker-common.yml
            service: django
        links:
            - redis
        entrypoint:
            - /worker-entrypoint.sh
    scheduler:
        extends:
            file: docker-common.yml
            service: django
        links:
            - redis
        entrypoint:
            - /scheduler-entrypoint.sh
        volumes:
            - ./docker/scheduler/data:/celerybeat
    redis:
        extends:
            file: docker-common.yml
            service: redis
