# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fb_emails', '0002_attachment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmessage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
