# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_emails', '0003_auto_20170302_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending processing'), ('unrecognized-domain', 'Unrecognized domain'), ('unrecognized-username', 'Unrecognized username'), ('issue-error', 'Failed creating issue'), ('processed', 'Processed'), ('sanitized', 'Sanitized')], default='pending', max_length=32),
        ),
    ]
