# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_emails', '0004_auto_20170331_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmessage',
            name='from_email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='from_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='subject',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='to_email',
            field=models.EmailField(max_length=500),
        ),
    ]
