# Generated by Django 2.2.10 on 2020-08-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_emails', '0005_auto_20170514_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='spam_score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
