# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import fb_github.models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_github', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='email_slug',
            field=models.SlugField(default=fb_github.models.email_slug_default, unique=True),
        ),
    ]
