# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fb_github', '0002_auto_20170223_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
