# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_github', '0003_auto_20170228_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmap',
            options={'ordering': ('created_at',)},
        ),
    ]
