# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fb_github', '0004_auto_20170301_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
