# Generated by Django 2.0.3 on 2018-04-03 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_github', '0008_auto_20170307_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='msg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fb_emails.IncomingMessage'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='initial_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fb_github.Issue'),
        ),
    ]
