# Generated by Django 2.0.4 on 2018-10-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_github', '0009_auto_20180403_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='include_sender_email_in_issue',
            field=models.BooleanField(default=True),
        ),
    ]
